% Inception v1

%% Parameters

EPSILON = 0.0010000000474974513;

%% load weights

mydir = 'inception_v1_float_weights\';
DIS = dir([mydir,'*.mat']);
n = length(DIS);

for i = 1:n
    data = load([mydir,DIS(i).name]);
%     eval([DIS(i).name(1:length(DIS(i).name)-4) ' = single(data.' DIS(i).name(1:length(DIS(i).name)-4) ');']); 
    eval([DIS(i).name(1:length(DIS(i).name)-4) ' = single(data.weights);']); 
end

% load input

mydir = 'C:/Users/Eugene/Documents/UCLA/Research/matlab_nn/tf_inception/image/';
DIS = dir([mydir,'*.mat']);
n = length(DIS);

for image = 1:n
    tic;
    value = load([mydir,DIS(image).name]);
%     value = imread(strcat(mydir, DIS(image).name));
    eval( 'input_image = value.image;');  

% input preprocessing
fm_input_data = single(squeeze(input_image));
% fm_input_data = single(reshape(input_image, 224, 224, 3));
% fm_input_data = permute(fm_input_data, [2, 1, 3]);


%% process each layer

%conv1 layer0
fm_conv1 = caffe_conv(fm_input_data, conv_1a_weights, 2, [2, 3]);
fm_conv1 = caffe_conv(fm_input_data, conv_1a_weights./sqrt(reshape(conv_1a_batchvar + EPSILON, 1, 1, 1, [])), 2, [2, 3]);
fm_conv1 = scale_add_bias(fm_conv1, -conv_1a_batchmean./sqrt(conv_1a_batchvar + EPSILON) + conv_1a_batchbeta);
fm_conv1 = caffe_relu(fm_conv1);

%pool1 layer1
fm_pool1 = caffe_pool(fm_conv1, 3, 2, [0, 1]);

%conv2 layer2
fm_conv2 = caffe_conv(fm_pool1, conv_2b_weights, 1, [0, 0]);
fm_conv2 = scale_add_bias(fm_conv2, -conv_2b_batchmean./sqrt(conv_2b_batchvar + EPSILON) + conv_2b_batchbeta);
fm_conv2 = caffe_relu(fm_conv2);

%conv3 layer3
fm_conv3 = caffe_conv(fm_conv2, conv_2c_weights./sqrt(reshape(conv_2c_batchvar + EPSILON, 1, 1, 1, [])), 1, [1, 1]);
fm_conv3 = scale_add_bias(fm_conv3, -conv_2c_batchmean./sqrt((conv_2c_batchvar + EPSILON)) + conv_2c_batchbeta);
fm_conv3 = caffe_relu(fm_conv3);

%pool2 layer4
fm_pool2 = caffe_pool(fm_conv3, 3, 2, [0, 1]);

%inception1 layer5
fm_inception1 = inception_layer(fm_pool2, ...
struct('weights', Mixed_3b_Branch_0_conv_0a_weights, 'batchmean', Mixed_3b_Branch_0_conv_0a_batchmean, 'batchvar', Mixed_3b_Branch_0_conv_0a_batchvar, ...
'batchbeta', Mixed_3b_Branch_0_conv_0a_batchbeta), ...
struct('weights_a', Mixed_3b_Branch_1_conv_0a_weights, 'batchmean_a', Mixed_3b_Branch_1_conv_0a_batchmean, 'batchvar_a', Mixed_3b_Branch_1_conv_0a_batchvar, ...
'batchbeta_a', Mixed_3b_Branch_1_conv_0a_batchbeta, 'weights_b', Mixed_3b_Branch_1_conv_0b_weights, 'batchmean_b', Mixed_3b_Branch_1_conv_0b_batchmean, ...
'batchvar_b', Mixed_3b_Branch_1_conv_0b_batchvar, 'batchbeta_b', Mixed_3b_Branch_1_conv_0b_batchbeta), ...
struct('weights_a', Mixed_3b_Branch_2_conv_0a_weights, 'batchmean_a', Mixed_3b_Branch_2_conv_0a_batchmean, 'batchvar_a', Mixed_3b_Branch_2_conv_0a_batchvar, ...
'batchbeta_a', Mixed_3b_Branch_2_conv_0a_batchbeta, 'weights_b', Mixed_3b_Branch_2_conv_0b_weights, 'batchmean_b', Mixed_3b_Branch_2_conv_0b_batchmean, ...
'batchvar_b', Mixed_3b_Branch_2_conv_0b_batchvar, 'batchbeta_b', Mixed_3b_Branch_2_conv_0b_batchbeta), ...
struct('weights', Mixed_3b_Branch_3_conv_0b_weights, 'batchmean', Mixed_3b_Branch_3_conv_0b_batchmean, 'batchvar', Mixed_3b_Branch_3_conv_0b_batchvar, ...
'batchbeta', Mixed_3b_Branch_3_conv_0b_batchbeta), EPSILON);

%inception2 layer6
fm_inception2 = inception_layer(fm_inception1, ...
struct('weights', Mixed_3c_Branch_0_conv_0a_weights, 'batchmean', Mixed_3c_Branch_0_conv_0a_batchmean, 'batchvar', Mixed_3c_Branch_0_conv_0a_batchvar, ...
'batchbeta', Mixed_3c_Branch_0_conv_0a_batchbeta), ...
struct('weights_a', Mixed_3c_Branch_1_conv_0a_weights, 'batchmean_a', Mixed_3c_Branch_1_conv_0a_batchmean, 'batchvar_a', Mixed_3c_Branch_1_conv_0a_batchvar, ...
'batchbeta_a', Mixed_3c_Branch_1_conv_0a_batchbeta, 'weights_b', Mixed_3c_Branch_1_conv_0b_weights, 'batchmean_b', Mixed_3c_Branch_1_conv_0b_batchmean, ...
'batchvar_b', Mixed_3c_Branch_1_conv_0b_batchvar, 'batchbeta_b', Mixed_3c_Branch_1_conv_0b_batchbeta), ...
struct('weights_a', Mixed_3c_Branch_2_conv_0a_weights, 'batchmean_a', Mixed_3c_Branch_2_conv_0a_batchmean, 'batchvar_a', Mixed_3c_Branch_2_conv_0a_batchvar, ...
'batchbeta_a', Mixed_3c_Branch_2_conv_0a_batchbeta, 'weights_b', Mixed_3c_Branch_2_conv_0b_weights, 'batchmean_b', Mixed_3c_Branch_2_conv_0b_batchmean, ...
'batchvar_b', Mixed_3c_Branch_2_conv_0b_batchvar, 'batchbeta_b', Mixed_3c_Branch_2_conv_0b_batchbeta), ...
struct('weights', Mixed_3c_Branch_3_conv_0b_weights, 'batchmean', Mixed_3c_Branch_3_conv_0b_batchmean, 'batchvar', Mixed_3c_Branch_3_conv_0b_batchvar, ...
'batchbeta', Mixed_3c_Branch_3_conv_0b_batchbeta), EPSILON);

%pool3 layer7
fm_pool3 = caffe_pool(fm_inception2, 3, 2, [0, 1]);

%inception3 layer8
fm_inception3 = inception_layer(fm_pool3, ...
struct('weights', Mixed_4b_Branch_0_conv_0a_weights, 'batchmean', Mixed_4b_Branch_0_conv_0a_batchmean, 'batchvar', Mixed_4b_Branch_0_conv_0a_batchvar, ...
'batchbeta', Mixed_4b_Branch_0_conv_0a_batchbeta), ...
struct('weights_a', Mixed_4b_Branch_1_conv_0a_weights, 'batchmean_a', Mixed_4b_Branch_1_conv_0a_batchmean, 'batchvar_a', Mixed_4b_Branch_1_conv_0a_batchvar, ...
'batchbeta_a', Mixed_4b_Branch_1_conv_0a_batchbeta, 'weights_b', Mixed_4b_Branch_1_conv_0b_weights, 'batchmean_b', Mixed_4b_Branch_1_conv_0b_batchmean, ...
'batchvar_b', Mixed_4b_Branch_1_conv_0b_batchvar, 'batchbeta_b', Mixed_4b_Branch_1_conv_0b_batchbeta), ...
struct('weights_a', Mixed_4b_Branch_2_conv_0a_weights, 'batchmean_a', Mixed_4b_Branch_2_conv_0a_batchmean, 'batchvar_a', Mixed_4b_Branch_2_conv_0a_batchvar, ...
'batchbeta_a', Mixed_4b_Branch_2_conv_0a_batchbeta, 'weights_b', Mixed_4b_Branch_2_conv_0b_weights, 'batchmean_b', Mixed_4b_Branch_2_conv_0b_batchmean, ...
'batchvar_b', Mixed_4b_Branch_2_conv_0b_batchvar, 'batchbeta_b', Mixed_4b_Branch_2_conv_0b_batchbeta), ...
struct('weights', Mixed_4b_Branch_3_conv_0b_weights, 'batchmean', Mixed_4b_Branch_3_conv_0b_batchmean, 'batchvar', Mixed_4b_Branch_3_conv_0b_batchvar, ...
'batchbeta', Mixed_4b_Branch_3_conv_0b_batchbeta), EPSILON);

%inception4 layer9
fm_inception4 = inception_layer(fm_inception3, ...
struct('weights', Mixed_4c_Branch_0_conv_0a_weights, 'batchmean', Mixed_4c_Branch_0_conv_0a_batchmean, 'batchvar', Mixed_4c_Branch_0_conv_0a_batchvar, ...
'batchbeta', Mixed_4c_Branch_0_conv_0a_batchbeta), ...
struct('weights_a', Mixed_4c_Branch_1_conv_0a_weights, 'batchmean_a', Mixed_4c_Branch_1_conv_0a_batchmean, 'batchvar_a', Mixed_4c_Branch_1_conv_0a_batchvar, ...
'batchbeta_a', Mixed_4c_Branch_1_conv_0a_batchbeta, 'weights_b', Mixed_4c_Branch_1_conv_0b_weights, 'batchmean_b', Mixed_4c_Branch_1_conv_0b_batchmean, ...
'batchvar_b', Mixed_4c_Branch_1_conv_0b_batchvar, 'batchbeta_b', Mixed_4c_Branch_1_conv_0b_batchbeta), ...
struct('weights_a', Mixed_4c_Branch_2_conv_0a_weights, 'batchmean_a', Mixed_4c_Branch_2_conv_0a_batchmean, 'batchvar_a', Mixed_4c_Branch_2_conv_0a_batchvar, ...
'batchbeta_a', Mixed_4c_Branch_2_conv_0a_batchbeta, 'weights_b', Mixed_4c_Branch_2_conv_0b_weights, 'batchmean_b', Mixed_4c_Branch_2_conv_0b_batchmean, ...
'batchvar_b', Mixed_4c_Branch_2_conv_0b_batchvar, 'batchbeta_b', Mixed_4c_Branch_2_conv_0b_batchbeta), ...
struct('weights', Mixed_4c_Branch_3_conv_0b_weights, 'batchmean', Mixed_4c_Branch_3_conv_0b_batchmean, 'batchvar', Mixed_4c_Branch_3_conv_0b_batchvar, ...
'batchbeta', Mixed_4c_Branch_3_conv_0b_batchbeta), EPSILON);

%inception5 layer10
fm_inception5 = inception_layer(fm_inception4, ...
struct('weights', Mixed_4d_Branch_0_conv_0a_weights, 'batchmean', Mixed_4d_Branch_0_conv_0a_batchmean, 'batchvar', Mixed_4d_Branch_0_conv_0a_batchvar, ...
'batchbeta', Mixed_4d_Branch_0_conv_0a_batchbeta), ...
struct('weights_a', Mixed_4d_Branch_1_conv_0a_weights, 'batchmean_a', Mixed_4d_Branch_1_conv_0a_batchmean, 'batchvar_a', Mixed_4d_Branch_1_conv_0a_batchvar, ...
'batchbeta_a', Mixed_4d_Branch_1_conv_0a_batchbeta, 'weights_b', Mixed_4d_Branch_1_conv_0b_weights, 'batchmean_b', Mixed_4d_Branch_1_conv_0b_batchmean, ...
'batchvar_b', Mixed_4d_Branch_1_conv_0b_batchvar, 'batchbeta_b', Mixed_4d_Branch_1_conv_0b_batchbeta), ...
struct('weights_a', Mixed_4d_Branch_2_conv_0a_weights, 'batchmean_a', Mixed_4d_Branch_2_conv_0a_batchmean, 'batchvar_a', Mixed_4d_Branch_2_conv_0a_batchvar, ...
'batchbeta_a', Mixed_4d_Branch_2_conv_0a_batchbeta, 'weights_b', Mixed_4d_Branch_2_conv_0b_weights, 'batchmean_b', Mixed_4d_Branch_2_conv_0b_batchmean, ...
'batchvar_b', Mixed_4d_Branch_2_conv_0b_batchvar, 'batchbeta_b', Mixed_4d_Branch_2_conv_0b_batchbeta), ...
struct('weights', Mixed_4d_Branch_3_conv_0b_weights, 'batchmean', Mixed_4d_Branch_3_conv_0b_batchmean, 'batchvar', Mixed_4d_Branch_3_conv_0b_batchvar, ...
'batchbeta', Mixed_4d_Branch_3_conv_0b_batchbeta), EPSILON);

%inception6 layer11
fm_inception6 = inception_layer(fm_inception5, ...
struct('weights', Mixed_4e_Branch_0_conv_0a_weights, 'batchmean', Mixed_4e_Branch_0_conv_0a_batchmean, 'batchvar', Mixed_4e_Branch_0_conv_0a_batchvar, ...
'batchbeta', Mixed_4e_Branch_0_conv_0a_batchbeta), ...
struct('weights_a', Mixed_4e_Branch_1_conv_0a_weights, 'batchmean_a', Mixed_4e_Branch_1_conv_0a_batchmean, 'batchvar_a', Mixed_4e_Branch_1_conv_0a_batchvar, ...
'batchbeta_a', Mixed_4e_Branch_1_conv_0a_batchbeta, 'weights_b', Mixed_4e_Branch_1_conv_0b_weights, 'batchmean_b', Mixed_4e_Branch_1_conv_0b_batchmean, ...
'batchvar_b', Mixed_4e_Branch_1_conv_0b_batchvar, 'batchbeta_b', Mixed_4e_Branch_1_conv_0b_batchbeta), ...
struct('weights_a', Mixed_4e_Branch_2_conv_0a_weights, 'batchmean_a', Mixed_4e_Branch_2_conv_0a_batchmean, 'batchvar_a', Mixed_4e_Branch_2_conv_0a_batchvar, ...
'batchbeta_a', Mixed_4e_Branch_2_conv_0a_batchbeta, 'weights_b', Mixed_4e_Branch_2_conv_0b_weights, 'batchmean_b', Mixed_4e_Branch_2_conv_0b_batchmean, ...
'batchvar_b', Mixed_4e_Branch_2_conv_0b_batchvar, 'batchbeta_b', Mixed_4e_Branch_2_conv_0b_batchbeta), ...
struct('weights', Mixed_4e_Branch_3_conv_0b_weights, 'batchmean', Mixed_4e_Branch_3_conv_0b_batchmean, 'batchvar', Mixed_4e_Branch_3_conv_0b_batchvar, ...
'batchbeta', Mixed_4e_Branch_3_conv_0b_batchbeta), EPSILON);

%inception7 layer12
fm_inception7 = inception_layer(fm_inception6, ...
struct('weights', Mixed_4f_Branch_0_conv_0a_weights, 'batchmean', Mixed_4f_Branch_0_conv_0a_batchmean, 'batchvar', Mixed_4f_Branch_0_conv_0a_batchvar, ...
'batchbeta', Mixed_4f_Branch_0_conv_0a_batchbeta), ...
struct('weights_a', Mixed_4f_Branch_1_conv_0a_weights, 'batchmean_a', Mixed_4f_Branch_1_conv_0a_batchmean, 'batchvar_a', Mixed_4f_Branch_1_conv_0a_batchvar, ...
'batchbeta_a', Mixed_4f_Branch_1_conv_0a_batchbeta, 'weights_b', Mixed_4f_Branch_1_conv_0b_weights, 'batchmean_b', Mixed_4f_Branch_1_conv_0b_batchmean, ...
'batchvar_b', Mixed_4f_Branch_1_conv_0b_batchvar, 'batchbeta_b', Mixed_4f_Branch_1_conv_0b_batchbeta), ...
struct('weights_a', Mixed_4f_Branch_2_conv_0a_weights, 'batchmean_a', Mixed_4f_Branch_2_conv_0a_batchmean, 'batchvar_a', Mixed_4f_Branch_2_conv_0a_batchvar, ...
'batchbeta_a', Mixed_4f_Branch_2_conv_0a_batchbeta, 'weights_b', Mixed_4f_Branch_2_conv_0b_weights, 'batchmean_b', Mixed_4f_Branch_2_conv_0b_batchmean, ...
'batchvar_b', Mixed_4f_Branch_2_conv_0b_batchvar, 'batchbeta_b', Mixed_4f_Branch_2_conv_0b_batchbeta), ...
struct('weights', Mixed_4f_Branch_3_conv_0b_weights, 'batchmean', Mixed_4f_Branch_3_conv_0b_batchmean, 'batchvar', Mixed_4f_Branch_3_conv_0b_batchvar, ...
'batchbeta', Mixed_4f_Branch_3_conv_0b_batchbeta), EPSILON);

%pool4 layer13
fm_pool4 = caffe_pool(fm_inception7, 2, 2, [0, 0]);

%inception8 layer14
fm_inception8 = inception_layer(fm_pool4, ...
struct('weights', Mixed_5b_Branch_0_conv_0a_weights, 'batchmean', Mixed_5b_Branch_0_conv_0a_batchmean, 'batchvar', Mixed_5b_Branch_0_conv_0a_batchvar, ...
'batchbeta', Mixed_5b_Branch_0_conv_0a_batchbeta), ...
struct('weights_a', Mixed_5b_Branch_1_conv_0a_weights, 'batchmean_a', Mixed_5b_Branch_1_conv_0a_batchmean, 'batchvar_a', Mixed_5b_Branch_1_conv_0a_batchvar, ...
'batchbeta_a', Mixed_5b_Branch_1_conv_0a_batchbeta, 'weights_b', Mixed_5b_Branch_1_conv_0b_weights, 'batchmean_b', Mixed_5b_Branch_1_conv_0b_batchmean, ...
'batchvar_b', Mixed_5b_Branch_1_conv_0b_batchvar, 'batchbeta_b', Mixed_5b_Branch_1_conv_0b_batchbeta), ...
struct('weights_a', Mixed_5b_Branch_2_conv_0a_weights, 'batchmean_a', Mixed_5b_Branch_2_conv_0a_batchmean, 'batchvar_a', Mixed_5b_Branch_2_conv_0a_batchvar, ...
'batchbeta_a', Mixed_5b_Branch_2_conv_0a_batchbeta, 'weights_b', Mixed_5b_Branch_2_conv_0b_weights, 'batchmean_b', Mixed_5b_Branch_2_conv_0b_batchmean, ...
'batchvar_b', Mixed_5b_Branch_2_conv_0b_batchvar, 'batchbeta_b', Mixed_5b_Branch_2_conv_0b_batchbeta), ...
struct('weights', Mixed_5b_Branch_3_conv_0b_weights, 'batchmean', Mixed_5b_Branch_3_conv_0b_batchmean, 'batchvar', Mixed_5b_Branch_3_conv_0b_batchvar, ...
'batchbeta', Mixed_5b_Branch_3_conv_0b_batchbeta), EPSILON);

%inception9 layer15
fm_inception9 = inception_layer(fm_inception8, ...
struct('weights', Mixed_5c_Branch_0_conv_0a_weights, 'batchmean', Mixed_5c_Branch_0_conv_0a_batchmean, 'batchvar', Mixed_5c_Branch_0_conv_0a_batchvar, ...
'batchbeta', Mixed_5c_Branch_0_conv_0a_batchbeta), ...
struct('weights_a', Mixed_5c_Branch_1_conv_0a_weights, 'batchmean_a', Mixed_5c_Branch_1_conv_0a_batchmean, 'batchvar_a', Mixed_5c_Branch_1_conv_0a_batchvar, ...
'batchbeta_a', Mixed_5c_Branch_1_conv_0a_batchbeta, 'weights_b', Mixed_5c_Branch_1_conv_0b_weights, 'batchmean_b', Mixed_5c_Branch_1_conv_0b_batchmean, ...
'batchvar_b', Mixed_5c_Branch_1_conv_0b_batchvar, 'batchbeta_b', Mixed_5c_Branch_1_conv_0b_batchbeta), ...
struct('weights_a', Mixed_5c_Branch_2_conv_0a_weights, 'batchmean_a', Mixed_5c_Branch_2_conv_0a_batchmean, 'batchvar_a', Mixed_5c_Branch_2_conv_0a_batchvar, ...
'batchbeta_a', Mixed_5c_Branch_2_conv_0a_batchbeta, 'weights_b', Mixed_5c_Branch_2_conv_0b_weights, 'batchmean_b', Mixed_5c_Branch_2_conv_0b_batchmean, ...
'batchvar_b', Mixed_5c_Branch_2_conv_0b_batchvar, 'batchbeta_b', Mixed_5c_Branch_2_conv_0b_batchbeta), ...
struct('weights', Mixed_5c_Branch_3_conv_0b_weights, 'batchmean', Mixed_5c_Branch_3_conv_0b_batchmean, 'batchvar', Mixed_5c_Branch_3_conv_0b_batchvar, ...
'batchbeta', Mixed_5c_Branch_3_conv_0b_batchbeta), EPSILON);

%pool5 layer16
fm_pool5 = caffe_avg_pool(fm_inception9, 7, 0);

%conv4 layer17
fm_conv4 = caffe_conv(fm_pool5, Logits_conv_0c_weights, 1, [0, 0]);
fm_conv4 = scale_add_bias(fm_conv4, Logits_conv_0c_biases);
fm_conv4 = squeeze(fm_conv4);

[~, write_output] = max(fm_conv4);
fid_layer1 = fopen(['result_' DIS(image).name(1:length(DIS(image).name)-14) '.txt'],'wt');
fprintf(fid_layer1, '%d\n', write_output);

toc;
fclose(fid_layer1);
end